# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy

# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy Azure WebApp resources using Terraform

on:
  workflow_dispatch:

jobs:

  deploy:
    name: Deploy Azure WebApp resources
    runs-on: ubuntu-latest
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          working-directory:  ./terraform

      - name: Log in to Azure using OIDC
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - run: |
          cd terraform
          pwd
          ls -l

      - name: Terraform install
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: 1.3.9

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform plan
        id: plan
        run: terraform plan

      - name: Terraform apply
        id: apply
        run: terraform apply -auto-approve